name: C/C++ CI

on: [push]

jobs:
  build:

    runs-on: ubuntu-latest
    
    steps:
    - uses: actions/checkout@v1
    - name: configure
      run: ./auto/configure
    - name: make
      run: make
    - name: package
      run: tar -cvzf nginx-objs.tar.gz objs/
    - uses: actions/upload-artifact@master
      with:
        name: nginx-objs.tar.gz
        path: nginx-objs.tar.gz
    
